### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by amyhenning** [Kellysalito/starlight#1]
Hey Kelly,

Great job with your Splurty app! It looks great, but on mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile. Try Googling "mobile meta tag" to see if you can find something to add to your code in the line highlighted in this link:

https://github.com/Kellysalito/starlight/blob/master/app/views/layouts/application.html.erb#L7

Let me know in the comments once you figure that step out :)

Thanks,

Amy

**Comment by Kellysalito** [comment]
Thanks! I added a meta tag, removed the hidden option for the "Splurting out..." on the top, and realized my URL wasn't linked to the app, so I added that too.

**Comment by amyhenning** [comment]
That's awesome, Kelly! Great work!
